:ems:
  :ems_ibm_cloud_power_virtual_servers:
    :event_handling:
      :event_groups:
        :power:
          :critical:
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_on
          - IBM_CLOUD_POWER_VIRTUAL_SERVERS_instance_power_off

:ems_refresh:
  :ibm_vpc:
    :refresh_interval: 15.minutes
  :ibm_cloud_power_virtual_servers:
    :refresh_interval: 15.minutes
    :storage_types:
    - :description: Tier 1 (NVMe-based flash storage)
      :state: active
      :type: tier1
    - :description: Tier 3 (SSD flash storage)
      :state: active
      :type: tier3
    - :description: SSD (Legacy)
      :state: active
      :type: ssd-legacy
    - :description: Standard (Legacy)
      :state: active
      :type: standard-legacy
:log:
  :level_ibm_cloud: info
:workers:
  :ems_refresh_worker_ibm_cloud_power_virtual_servers:
    :inherits_from: ems_refresh_worker
  :ems_refresh_worker_ibm_cloud_vpc:
    :inherits_from: ems_refresh_worker
  :event_catcher_ibm_cloud_power_virtual_servers:
    :inherits_from: event_catcher
    :poll: 20.seconds
